### ISSUE TITLE
couple of questions

### ISSUE THREAD

**Issue by dutchsing009** [dtx525942103/vits-singing-voice-synthesis#3]
Hello how are you ! very cool stuff you have here ,I can clearly see you love singing voice synthesis (SVS) from your forks and repos !!
i wanted to ask is that a fully working Visingerr or is it a try from you to make it to sing , like can it be tested on a custom English data and have like results the same as or near the demo in the paper. Also do you have like other samples i can hear , i know that you tested it on opencpop that has almost 5.2 hours of singing data , and also in the paper they trained Visingerr for 600k iterations right ? how many iterations did you achieve on the opencpop to get the result linked below (vits_singing_样例.wav). 
to be honest i thought vits is data hungry like tacotron2 or fastspeech (aka needs a lot of data to get great results) , that opencpop result of your is so impressive for 5.2 hours data , i also wonder if you lowered the sample rate of opencpop from 44.1 KHz to 22KHz as i heard 44.1 KHz takes alot of time to train x10 the time needed.

迫不及待地想知道你的消息 :)

**Comment by dtx525942103** [comment]
I have not succeeded in implementing VISinger，this repo needs f0 as input

**Comment by dutchsing009** [comment]
oh ok so you need someone to add f0 to losses.py and vsinging_hifi_debug.py for it to fully work right ?

**Comment by dtx525942103** [comment]
need client software like utau/VOCALOID to draw f0 curve as input

**Comment by dutchsing009** [comment]
ah ok i'm trying to help too ,, have you seen / tried that repo , https://github.com/congzhang365/private-praat-scripts ??? or that https://github.com/lennes/spect/tree/master/scripts ?

**Comment by dtx525942103** [comment]
here，need draw f0 curve from midi note;  the f0 is not extracted from wave when infer; 
maybe like this, but need more detail of f0

    def scorePitch(self, scores_id):
        score_pitch = np.zeros(len(scores_id), dtype=np.float)
        for index, score_id in enumerate(scores_id):
            if score_id == 0:
                score_pitch[index] = 0
            else:
                pitch = librosa.midi_to_hz(score_id)
                score_pitch[index] = round(pitch, 1)
        return score_pitch
