### ISSUE TITLE
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'

### ISSUE THREAD

**Issue by baipeng0110** [dtx525942103/vits-singing-voice-synthesis#7]
似乎是内存满了报错，我用的是1080的卡8GB显存，是不是不够？您用的什么卡？
还有我也尝试训练了，官方的VITS在LJ-speech数据集上，但是也是报错显存溢出，但是那个源代码是多卡训练的，请问您是否自己试过？至少得有多少显存才能训？而且我都把batch-size调到8了也不行。盼回复

**Comment by dtx525942103** [comment]
1080Ti，我的是16K的音频，您是24K么？

**Comment by baipeng0110** [comment]
您的邮件我已经收到，会尽快回复，谢谢。

**Comment by baipeng0110** [comment]
> 1080Ti，我的是16K的音频，您是24K么？

我就是按照您的那个  转化为16k做的，就跑的您这个开源项目

**Comment by dtx525942103** [comment]
12G显存没问题，8G应该不太行，因为有6G是pytorch固定预留的

**Comment by baipeng0110** [comment]
> 

好的 了解了 刚入门语音合成，感谢回复
