### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by baipeng0110** [dtx525942103/vits-singing-voice-synthesis#9]
python prepare/data_vits.py 输出 1,../VISinger_data/label_vits/XXX._label.npy|XXX_score.npy|XXX_pitch.npy|XXX_slurs.npy 2,filelists/vits_file.txt 内容格式：wave path|label path|score path|pitch path|slurs path;

请问1 2这两步是怎么操作？

**Comment by dtx525942103** [comment]
这是一步，python prepare/data_vits.py

**Comment by baipeng0110** [comment]
您的邮件我已经收到，会尽快回复，谢谢。

**Comment by baipeng0110** [comment]
您的邮件我已经收到，会尽快回复，谢谢。
